// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include <functional>

#include "CoreMinimal.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "FunctionLib.generated.h"

/*
 * my object iterator, taking into account the World via `UWorld*` param in the constructor
 * 
 * For PIE multiplayer-testing: with `Run under one process` checked, the `TObjectIterator` iterates
 * through all worlds, across host and client; this one can be restricted, e.g.
 * 
 for(MyObjectIterator<SomeActorComponent> IComponent(GetWorld()); IComponent; ++IComponent)
 {
	// components are filtered already according to `(*IComponent)->GetWorld() == GetWorld()`
	(*IComponent)->SomeMethod();
 }
 */
template<class TUObject>
struct TMyObjectIterator : TObjectIterator<TUObject>
{
	typedef std::function<bool (const TUObject*) > FFilterFunc;

	TMyObjectIterator()
		: FilterFunc([] (const TUObject*) { return true; })
	{
	}

	TMyObjectIterator(const UWorld* World)
		: FilterFunc([World] (const TUObject* Object)
			{
				return Object->GetWorld() == World;
			})
	{
	}
	
	TMyObjectIterator(FFilterFunc InFilterFunc)
		: FilterFunc(InFilterFunc)
	{
		while(*this && !FilterFunc(**this))
		{
			++*this;
		}
	}

	// prefix inc
	TMyObjectIterator& operator++()
	{
		do
		{
			TObjectIterator<TUObject>::operator++();
		} while (*this && !FilterFunc(**this));
		return *this;
	}
	
	// suffix inc
	TMyObjectIterator operator++(int)
	{
		TMyObjectIterator Copy = *this;
		++*this;
		return Copy;
	}

private:
	FFilterFunc FilterFunc;
};

/**
 * 
 */
UCLASS()
class MURDERINSPACE_API UFunctionLib : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()

public:
	UFUNCTION(BlueprintPure, Category="Orbit")
	static FVector VecVelocity(FVector E, FVector R, FVector VecH, double Alpha, FVector Default);
	
	UFUNCTION(BlueprintPure, Category="Orbit")
	static double ScalarVelocitySquared(double R, double A, double Alpha);

	// the velocity at r=inf, or "excess velocity"
	// when the trajectory is bound, the excess velocity is undefined
	UFUNCTION(BlueprintPure, Category="Orbit")
	static double VelocityInfinity(double E);
	
	UFUNCTION(BlueprintPure, Category="Orbit")
	static FVector Eccentricity(FVector R, FVector V, double Alpha);

	UFUNCTION(BlueprintPure, Category="Orbit")
	static FVector FocusPoint2(double A, FVector E);

	UFUNCTION(BlueprintPure, Category="Orbit")
	static double SemiMajorAxis(FVector VecR, FVector VecV, double Alpha);

	UFUNCTION(BlueprintPure, Category="Orbit")
	static double SemiMinorAxis(double A, double ESquared);

	UFUNCTION(BlueprintPure, Category="Orbit")
	static double PeriodEllipse(double A, double Alpha);

	UFUNCTION(BlueprintPure, Category="Orbit")
	static double Perimeter(double A, double B);

	UFUNCTION(BlueprintPure, Category="Orbit")
	static double AxialTidalForce(double R, double L, double M, double Alpha);

	static constexpr int LengthSatellites = 854;
	static inline FString Satellites[LengthSatellites] =
		{ "3D-Winds"
		, "ACE"
		, "ACE (Aer.Clo.Eco.)"
		, "ACRIMSat"
		, "ADEOS"
		, "ADEOS-2"
		, "Aditya-1"
		, "Aeolus"
		, "ALOS"
		, "ALOS-2"
		, "ALOS-3"
		, "ALOS-4"
		, "AlSat-1"
		, "AlSat-1B"
		, "AlSat-2"
		, "AlSat-2B"
		, "ALTIUS"
		, "Amazônia-1"
		, "Amazônia-1B"
		, "Amazônia-2"
		, "Aqua"
		, "Arctica-M N1"
		, "Arctica-M N2"
		, "Arctica-M N3"
		, "Arctica-M N4"
		, "Arctica-M N5"
		, "ARGOS-4"
		, "ARTEMIS-P1"
		, "ARTEMIS-P2"
		, "ASCENDS"
		, "ASNARO-1"
		, "ASNARO-2"
		, "ATS-1"
		, "ATS-3"
		, "ATS-6"
		, "Aura"
		, "AWS"
		, "AWS-PFM"
		, "Beijing-1"
		, "BILSat"
		, "BIOMASS"
		, "BIRD"
		, "BlackSky-1"
		, "BlackSky-10"
		, "BlackSky-11"
		, "BlackSky-12"
		, "BlackSky-13"
		, "BlackSky-14"
		, "BlackSky-15"
		, "BlackSky-16"
		, "BlackSky-17"
		, "BlackSky-2"
		, "BlackSky-3"
		, "BlackSky-4"
		, "BlackSky-5"
		, "BlackSky-6"
		, "BlackSky-7"
		, "BlackSky-8"
		, "BlackSky-9"
		, "C/NOFS"
		, "CALIPSO"
		, "Capella"
		, "CarbonSat"
		, "CartoSat-1 (IRS-P5)"
		, "CartoSat-2"
		, "CartoSat-2A"
		, "CartoSat-2B"
		, "CartoSat-2C"
		, "CartoSat-2D"
		, "CartoSat-2E"
		, "CartoSat-2F"
		, "CartoSat-3"
		, "CAS 500-1"
		, "CAS 500-2"
		, "CASSIOPE"
		, "CBERS-1"
		, "CBERS-2"
		, "CBERS-2B"
		, "CBERS-3"
		, "CBERS-4"
		, "CBERS-4B"
		, "CFOSAT"
		, "CFOSAT follow-on"
		, "CHAMP"
		, "CHIME"
		, "CICERO"
		, "CICERO-2"
		, "CIMR"
		, "CLARREO-1A"
		, "CLARREO-1B"
		, "CLARREO-2A"
		, "CLARREO-2B"
		, "CloudSat"
		, "CLUSTER-A"
		, "CLUSTER-B"
		, "CLUSTER-C"
		, "CLUSTER-D"
		, "CO2M"
		, "COMPIRA"
		, "COMS"
		, "Coriolis"
		, "Coronas-F"
		, "Coronas-I"
		, "Coronas-Photon"
		, "COSMIC-1"
		, "COSMIC-2"
		, "COSMIC-2b"
		, "CRISTAL"
		, "CRRES"
		, "CryoSat"
		, "CryoSat-2"
		, "CSG-1"
		, "CSG-2"
		, "CSG-3"
		, "CSG-4"
		, "CSIM"
		, "CSK-1"
		, "CSK-2"
		, "CSK-3"
		, "CSK-4"
		, "CYGNSS (8 sats)"
		, "Deimos-1"
		, "Deimos-2"
		, "DESDynI"
		, "Diadéme-1"
		, "Diadéme-2"
		, "DMSP-F01"
		, "DMSP-F02"
		, "DMSP-F03"
		, "DMSP-F04"
		, "DMSP-F05"
		, "DMSP-F06"
		, "DMSP-F07"
		, "DMSP-F08"
		, "DMSP-F09"
		, "DMSP-F10"
		, "DMSP-F11"
		, "DMSP-F12"
		, "DMSP-F13"
		, "DMSP-F14"
		, "DMSP-F15"
		, "DMSP-F16"
		, "DMSP-F17"
		, "DMSP-F18"
		, "DMSP-F19"
		, "DQ-1"
		, "DQ-2"
		, "DSCOVR"
		, "DubaiSat-1"
		, "DubaiSat-2"
		, "DubaiSat-3"
		, "EarthCARE"
		, "EDRS-C"
		, "EgyptSat-1"
		, "EgyptSat-2"
		, "EgyptSat-A"
		, "Electro-GOMS"
		, "Electro-L N1"
		, "Electro-L N2"
		, "Electro-L N3"
		, "Electro-L N4"
		, "Electro-L N5"
		, "Electro-M N1"
		, "Electro-M N2"
		, "Electro-M N3"
		, "EnMAP"
		, "Envisat"
		, "EOS 03"
		, "EOS-01"
		, "EOS-04"
		, "ERBS"
		, "ERG"
		, "ERS-1"
		, "ERS-2"
		, "ESSA-1"
		, "ESSA-2"
		, "ESSA-3"
		, "ESSA-4"
		, "ESSA-5"
		, "ESSA-6"
		, "ESSA-7"
		, "ESSA-8"
		, "ESSA-9"
		, "Explorer-VII"
		, "Falcon-Eye 1"
		, "Falcon-Eye 2"
		, "FLEX"
		, "FLOCK"
		, "FORMOSAT-1"
		, "FORMOSAT-2"
		, "FORMOSAT-5"
		, "FORUM"
		, "FY-1A"
		, "FY-1B"
		, "FY-1C"
		, "FY-1D"
		, "FY-2A"
		, "FY-2B"
		, "FY-2C"
		, "FY-2D"
		, "FY-2E"
		, "FY-2F"
		, "FY-2G"
		, "FY-2H"
		, "FY-3A"
		, "FY-3B"
		, "FY-3C"
		, "FY-3D"
		, "FY-3E"
		, "FY-3F"
		, "FY-3G"
		, "FY-3H"
		, "FY-3I"
		, "FY-3J"
		, "FY-4 MW1"
		, "FY-4A"
		, "FY-4B"
		, "FY-4C"
		, "FY-4D"
		, "FY-4E"
		, "FY-4F"
		, "FY-4G"
		, "GACM"
		, "Galileo"
		, "GCOM-C"
		, "GCOM-W"
		, "GEO-CAPE"
		, "GEO-KOMPSAT-2A"
		, "GEO-KOMPSAT-2B"
		, "GeoCarb"
		, "GeoEye-1"
		, "GEOSat"
		, "GEOTAIL"
		, "GF-1"
		, "GF-1-02"
		, "GF-1-03"
		, "GF-1-04"
		, "GF-10"
		, "GF-11"
		, "GF-11-02"
		, "GF-11-03"
		, "GF-12"
		, "GF-12-02"
		, "GF-12-03"
		, "GF-13"
		, "GF-14"
		, "GF-2"
		, "GF-3"
		, "GF-3-02"
		, "GF-3-03"
		, "GF-4"
		, "GF-5"
		, "GF-5-02"
		, "GF-6"
		, "GF-7"
		, "GF-8"
		, "GF-9"
		, "GF-9-02"
		, "GF-9-03"
		, "GF-9-04"
		, "GF-9-05"
		, "GFO"
		, "GFZ-1"
		, "GHGSat"
		, "GISAT-2"
		, "Glory"
		, "GNOMES-1"
		, "GNOMES-2"
		, "GNOMES-3"
		, "GOCE"
		, "GOES-1"
		, "GOES-10"
		, "GOES-10 (S-America)"
		, "GOES-11"
		, "GOES-12"
		, "GOES-12 (S-America)"
		, "GOES-13"
		, "GOES-14"
		, "GOES-15"
		, "GOES-16"
		, "GOES-17"
		, "GOES-18"
		, "GOES-2"
		, "GOES-3"
		, "GOES-4"
		, "GOES-5"
		, "GOES-6"
		, "GOES-7"
		, "GOES-8"
		, "GOES-9"
		, "GOES-9 (GMS backup)"
		, "GOES-U"
		, "Göktürk-1A"
		, "Göktürk-2"
		, "GOSAT"
		, "GOSAT-2"
		, "GOSAT-GW"
		, "GPM Core Observatory"
		, "GRACE (2 sats)"
		, "GRACE-FO (2 sats)"
		, "HCMM"
		, "Himawari-1 (GMS-1)"
		, "Himawari-2 (GMS-2)"
		, "Himawari-3 (GMS-3)"
		, "Himawari-4 (GMS-4)"
		, "Himawari-5 (GMS-5)"
		, "Himawari-6 (MTSAT-1R)"
		, "Himawari-7 (MTSAT-2)"
		, "Himawari-8"
		, "Himawari-9"
		, "HJ-1A"
		, "HJ-1B"
		, "HJ-1C"
		, "HJ-2A"
		, "HJ-2B"
		, "HRSAT-1A"
		, "HRSAT-1B"
		, "HRSAT-1C"
		, "HRWS-SAR"
		, "HY-1A"
		, "HY-1B"
		, "HY-1C"
		, "HY-1D"
		, "HY-1E"
		, "HY-1F"
		, "HY-2A"
		, "HY-2B"
		, "HY-2C"
		, "HY-2D"
		, "HY-2E"
		, "HY-2F"
		, "HY-2G"
		, "HY-2H"
		, "HY-3A"
		, "HY-3B"
		, "HY-3C"
		, "HY-3D"
		, "HySIS"
		, "HyspIRI"
		, "IBEX"
		, "ICESat"
		, "ICESat-2"
		, "ICEYE"
		, "ICON"
		, "Ikonos"
		, "IMAGE"
		, "IMS-1"
		, "INSAT-1A"
		, "INSAT-1B"
		, "INSAT-1C"
		, "INSAT-1D"
		, "INSAT-2A"
		, "INSAT-2B"
		, "INSAT-2C"
		, "INSAT-2D"
		, "INSAT-2E"
		, "INSAT-3A"
		, "INSAT-3B"
		, "INSAT-3C"
		, "INSAT-3D"
		, "INSAT-3DR"
		, "INSAT-3DS"
		, "Ionosphera-M N1 & N2"
		, "Ionosphera-M N3 & N4"
		, "IRIS"
		, "IRS-1A"
		, "IRS-1B"
		, "IRS-1C"
		, "IRS-1D"
		, "IRS-1E (IRS-P1)"
		, "IRS-P2"
		, "IRS-P3"
		, "ISS ASIM"
		, "ISS CATS"
		, "ISS CLARREO-PF"
		, "ISS COWVR"
		, "ISS DESIS"
		, "ISS ECOSTRESS"
		, "ISS GARI"
		, "ISS GEDI"
		, "ISS HICO"
		, "ISS HISUI"
		, "ISS LIS"
		, "ISS MOLI"
		, "ISS OCO-3"
		, "ISS RainCube"
		, "ISS RapidScat"
		, "ISS SAGE-III"
		, "ISS TEMPEST-1"
		, "ISS TEMPEST-D"
		, "ISS TSIS-1"
		, "ISS TSIS-2"
		, "ITOS-1 (TIROS-M)"
		, "JASON-1"
		, "JASON-2"
		, "JASON-3"
		, "JERS"
		, "Jilin-1"
		, "JPSS-2"
		, "JPSS-3"
		, "JPSS-4"
		, "Kalpana-1"
		, "KANOPUS-V-IK-1"
		, "KANOPUS-V1"
		, "KANOPUS-V3"
		, "KANOPUS-V4"
		, "KANOPUS-V5"
		, "KANOPUS-V6"
		, "KazEOSat-1"
		, "KazEOSat-2"
		, "KOMPSAT-1"
		, "KOMPSAT-2"
		, "KOMPSAT-3"
		, "KOMPSAT-3A"
		, "KOMPSAT-5"
		, "KOMPSAT-6"
		, "KOMPSAT-7"
		, "Kondor-E"
		, "Kondor-E1"
		, "LAGEOS-1"
		, "LAGEOS-2"
		, "Landsat-1 (ERTS)"
		, "Landsat-2"
		, "Landsat-3"
		, "Landsat-4"
		, "Landsat-5"
		, "Landsat-6"
		, "Landsat-7"
		, "Landsat-8"
		, "Landsat-9"
		, "LARES-1"
		, "Lemur-2"
		, "LIST"
		, "LSTM"
		, "MAIA"
		, "MATS"
		, "Megha-Tropiques"
		, "MERLIN"
		, "Meteor-1-1"
		, "Meteor-1-10"
		, "Meteor-1-11"
		, "Meteor-1-12"
		, "Meteor-1-13"
		, "Meteor-1-14"
		, "Meteor-1-15"
		, "Meteor-1-16"
		, "Meteor-1-17"
		, "Meteor-1-19"
		, "Meteor-1-2"
		, "Meteor-1-20"
		, "Meteor-1-21"
		, "Meteor-1-22"
		, "Meteor-1-23"
		, "Meteor-1-24"
		, "Meteor-1-26"
		, "Meteor-1-27"
		, "Meteor-1-3"
		, "Meteor-1-4"
		, "Meteor-1-5"
		, "Meteor-1-6"
		, "Meteor-1-7"
		, "Meteor-1-8"
		, "Meteor-1-9"
		, "Meteor-2-1"
		, "Meteor-2-10"
		, "Meteor-2-11"
		, "Meteor-2-12"
		, "Meteor-2-13"
		, "Meteor-2-14"
		, "Meteor-2-15"
		, "Meteor-2-16"
		, "Meteor-2-17"
		, "Meteor-2-18"
		, "Meteor-2-19"
		, "Meteor-2-2"
		, "Meteor-2-20"
		, "Meteor-2-21"
		, "Meteor-2-3"
		, "Meteor-2-4"
		, "Meteor-2-5"
		, "Meteor-2-6"
		, "Meteor-2-7"
		, "Meteor-2-8"
		, "Meteor-2-9"
		, "Meteor-3-1"
		, "Meteor-3-2"
		, "Meteor-3-3"
		, "Meteor-3-4"
		, "Meteor-3-5"
		, "Meteor-3-6"
		, "Meteor-3M"
		, "Meteor-M N1"
		, "Meteor-M N2"
		, "Meteor-M N2-1"
		, "Meteor-M N2-2"
		, "Meteor-M N2-3"
		, "Meteor-M N2-4"
		, "Meteor-M N2-5"
		, "Meteor-M N2-6"
		, "Meteor-MP N1"
		, "Meteor-MP N2"
		, "Meteor-P1"
		, "Meteor-P2"
		, "Meteor-P3"
		, "Meteor-P4"
		, "Meteor-P5"
		, "Meteor-P6"
		, "Meteosat-1"
		, "Meteosat-10"
		, "Meteosat-11"
		, "Meteosat-2"
		, "Meteosat-3"
		, "Meteosat-3 (ADC)"
		, "Meteosat-3 (X-ADC)"
		, "Meteosat-4"
		, "Meteosat-5"
		, "Meteosat-5 (IODC)"
		, "Meteosat-6"
		, "Meteosat-6 (IODC)"
		, "Meteosat-7"
		, "Meteosat-7 (IODC)"
		, "Meteosat-8"
		, "Meteosat-8 (IODC)"
		, "Meteosat-9"
		, "Meteosat-9 (IODC)"
		, "Metop-A"
		, "Metop-B"
		, "Metop-C"
		, "Metop-SG-A1"
		, "Metop-SG-A2"
		, "Metop-SG-A3"
		, "Metop-SG-B1"
		, "Metop-SG-B2"
		, "Metop-SG-B3"
		, "MicroCarb"
		, "MIMAN"
		, "MISTiC Winds"
		, "MMS-A"
		, "MMS-B"
		, "MMS-C"
		, "MMS-D"
		, "Mohammed VI-A"
		, "Mohammed VI-B"
		, "Monitor-E"
		, "MOS-1"
		, "MOS-1B"
		, "MTG-I1"
		, "MTG-I2"
		, "MTG-I3"
		, "MTG-I4"
		, "MTG-S1"
		, "MTG-S2"
		, "NACHOS-1"
		, "NACHOS-2"
		, "NEMO-AM"
		, "NI-SAR"
		, "NigeriaSat-1"
		, "NigeriaSat-2"
		, "NigeriaSat-X"
		, "Nimbus-1"
		, "Nimbus-2"
		, "Nimbus-3"
		, "Nimbus-4"
		, "Nimbus-5"
		, "Nimbus-6"
		, "Nimbus-7"
		, "NMP-EO-1"
		, "NOAA-1"
		, "NOAA-10"
		, "NOAA-11"
		, "NOAA-12"
		, "NOAA-13"
		, "NOAA-14"
		, "NOAA-15"
		, "NOAA-16"
		, "NOAA-17"
		, "NOAA-18"
		, "NOAA-19"
		, "NOAA-2"
		, "NOAA-20"
		, "NOAA-3"
		, "NOAA-4"
		, "NOAA-5"
		, "NOAA-6"
		, "NOAA-7"
		, "NOAA-8"
		, "NOAA-9"
		, "NovaSAR-S"
		, "ÑuSat     "
		, "Obzor-O N1"
		, "Obzor-O N2"
		, "Obzor-O N3"
		, "Obzor-O N4"
		, "Obzor-R N1"
		, "Obzor-R N2"
		, "Obzor-R N3"
		, "Obzor-R N4"
		, "OceanSat-1 (IRS-P4)"
		, "OceanSat-2"
		, "OceanSat-3"
		, "OceanSat-3A"
		, "OCO"
		, "OCO-2"
		, "Odin"
		, "Okean-O-1"
		, "Okean-O1-1"
		, "Okean-O1-2"
		, "Okean-O1-3"
		, "Okean-O1-4"
		, "Okean-O1-5"
		, "Okean-O1-6"
		, "Okean-O1-7"
		, "OrbView-1/MicroLab"
		, "OrbView-2/SeaStar"
		, "OrbView-3"
		, "OrbView-4"
		, "Ørsted"
		, "PACE"
		, "PARASOL"
		, "Parker Solar Probe"
		, "PATH"
		, "PCW-1"
		, "PCW-2"
		, "PeruSat-1"
		, "Picard"
		, "Pléiades-1A"
		, "Pléiades-1B"
		, "Pléiades-Neo 3"
		, "Pléiades-Neo 4"
		, "Pléiades-Neo C"
		, "Pléiades-Neo D"
		, "Polar"
		, "PREFIRE"
		, "PRISMA"
		, "PROBA-1"
		, "PROBA-2"
		, "PROBA-V"
		, "PUNCH"
		, "QuickBird"
		, "QuickSounder"
		, "QuikSCAT"
		, "RadarSat-1"
		, "RadarSat-2"
		, "RapidEye (5 sats)"
		, "RASAT"
		, "RCM-1"
		, "RCM-2"
		, "RCM-3"
		, "ResourceSat-1 (IRS-P6)"
		, "ResourceSat-2"
		, "ResourceSat-2A"
		, "ResourceSat-3"
		, "ResourceSat-3A"
		, "ResourceSat-3S"
		, "ResourceSat-3SA"
		, "Resurs-DK"
		, "Resurs-O1-1"
		, "Resurs-O1-2"
		, "Resurs-O1-3"
		, "Resurs-O1-4"
		, "Resurs-P1"
		, "Resurs-P2"
		, "Resurs-P3"
		, "Resurs-P4"
		, "Resurs-P5"
		, "RHESSI"
		, "RISAT-1"
		, "RISAT-2"
		, "RISAT-2B"
		, "RISAT-2BR1"
		, "ROSE-L"
		, "SAC-A"
		, "SAC-B"
		, "SAC-C"
		, "SAC-D"
		, "SAC-E/SABIA-MAR A"
		, "SAC-E/SABIA-MAR B"
		, "SAMPEX"
		, "SAOCOM-1A"
		, "SAOCOM-1B"
		, "SAOCOM-2A"
		, "SAOCOM-2B"
		, "SARAL"
		, "ScatSat-1"
		, "SCD-1"
		, "SCD-2"
		, "SCISAT-1"
		, "SCLP"
		, "SDO"
		, "SeaSat"
		, "Sentinel-1A"
		, "Sentinel-1B"
		, "Sentinel-1C"
		, "Sentinel-1D"
		, "Sentinel-2A"
		, "Sentinel-2B"
		, "Sentinel-2C"
		, "Sentinel-2D"
		, "Sentinel-3A"
		, "Sentinel-3B"
		, "Sentinel-3C"
		, "Sentinel-3D"
		, "Sentinel-5P"
		, "Sentinel-6A"
		, "Sentinel-6B"
		, "SEOSAR/Paz"
		, "SEOSat/Ingenio"
		, "SES-14"
		, "SICH-1"
		, "SICH-1M"
		, "SICH-2"
		, "SICH-2-30"
		, "SJ-9A"
		, "SJ-9B"
		, "SkySat-1"
		, "SkySat-10"
		, "SkySat-11"
		, "SkySat-12"
		, "SkySat-13"
		, "SkySat-14"
		, "SkySat-15"
		, "SkySat-16"
		, "SkySat-17"
		, "SkySat-18"
		, "SkySat-19"
		, "SkySat-2"
		, "SkySat-20"
		, "SkySat-21"
		, "SkySat-3"
		, "SkySat-4"
		, "SkySat-5"
		, "SkySat-6"
		, "SkySat-7"
		, "SkySat-8"
		, "SkySat-9"
		, "SMAP"
		, "SMM"
		, "SMOS"
		, "SMS-1"
		, "SMS-2"
		, "SNPP"
		, "SOHO"
		, "Solar Orbiter"
		, "Solar-A (Yohkoh)"
		, "Solar-B (Hinode)"
		, "SORCE"
		, "SPOT-1"
		, "SPOT-2"
		, "SPOT-3"
		, "SPOT-4"
		, "SPOT-5"
		, "SPOT-6"
		, "SPOT-7"
		, "SSOT"
		, "SSTL-S1 1"
		, "SSTL-S1 2"
		, "SSTL-S1 3"
		, "SSTL-S1 4"
		, "STARLETTE"
		, "STELLA"
		, "STEREO-A"
		, "STEREO-B"
		, "STPSat-1"
		, "STPSat-2"
		, "STPSat-3"
		, "StriX-1"
		, "StriX-α"
		, "StriX-β"
		, "STSat-1"
		, "STSat-2"
		, "STSat-2C"
		, "STSat-3"
		, "SumbandilaSat"
		, "SuperView Neo-1 01"
		, "SuperView Neo-1 02"
		, "SuperView Neo-2 01"
		, "SuperView Neo-2 02"
		, "SuperView-1"
		, "SuperView-2"
		, "SuperView-3"
		, "SuperView-4"
		, "SWARM-A"
		, "SWARM-B"
		, "SWARM-C"
		, "SWFO-L1"
		, "SWOT"
		, "TacSat-2"
		, "Tandem-L"
		, "TanDEM-X"
		, "TANSAT"
		, "TEMPO"
		, "Terra"
		, "TerraSAR-X"
		, "TH-1A"
		, "TH-1B"
		, "TH-1C"
		, "THEMIS-A"
		, "THEMIS-D"
		, "THEMIS-E"
		, "THEOS-1"
		, "THEOS-2 Main"
		, "THEOS-2 Small"
		, "TIMED"
		, "TIROS-1"
		, "TIROS-10"
		, "TIROS-2"
		, "TIROS-3"
		, "TIROS-4"
		, "TIROS-5"
		, "TIROS-6"
		, "TIROS-7"
		, "TIROS-8"
		, "TIROS-9"
		, "TIROS-N"
		, "TOMS Earth Probe"
		, "TOPEX-Poseidon"
		, "TopSat"
		, "TRACE"
		, "TRISHNA"
		, "TRMM"
		, "TROPICS-01 (Pathfinder)"
		, "TROPICS-02"
		, "TROPICS-03"
		, "TROPICS-04"
		, "TROPICS-05"
		, "TROPICS-06"
		, "TROPICS-07"
		, "TRUTHS"
		, "TWINS (2 sats)"
		, "UARS"
		, "UK-DMC-1"
		, "UK-DMC-2"
		, "UMBRA"
		, "VAP (2 sat)"
		, "VENµS"
		, "Vigil-L5"
		, "VNREDSat-1"
		, "VRSS-1"
		, "VRSS-2"
		, "WIND"
		, "WorldView-1"
		, "WorldView-2"
		, "WorldView-3"
		, "WorldView-4"
		, "WSF-M1"
		, "X-Sat"
		, "XMM-Newton"
		, "XOVWM"
		, "Zond-M"
		, "ZY-1-2C"
		, "ZY-1-2D"
		, "ZY-3-01"
		, "ZY-3-02"
		, "ZY-3-03"
		};
};

inline void With(UObject* Object, const FString& Name, std::function<void(UObject*)> Func)
{
	if(IsValid(Object))
	{
		Func(Object);
	}
	else
	{
		UE_LOG
			( LogEngine
			, Error
			, TEXT("With: %s null")
			, *Name
			)
	}
}